name: Build & upload to Firebase App Distribution 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      PACKAGE_NAME: "com.vita.app"
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3

      # Get flutter sdk
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      # Get flutter dependencies
      - name: Install flutter dependencies
        run: flutter pub get
        
      # Get object box library to local machine
      - name: Install object box to local machine
        run: bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)
      
      # Update localization
      - name: Build all localization file
        run: flutter gen-l10n
      
      # Build all generated file
      - name: Build all generated file
        run: flutter pub run build_runner build --delete-conflicting-outputs
     
      # Run all unit test
      - name: Run tests
        run: flutter test
 
      # Set Java
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
         java-version: '12.x'
        
      # Enable flutter fire
      - name: Enable flutter fire
        run: dart pub global activate flutterfire_cli
      
      # Install firebase tools
      - name: Install firebase tools
        run: curl -sL https://firebase.tools | bash
      
      # Configure firebase
      - name: Configure flutter fire to add google service file
        run: flutterfire configure --project=vita-377401 --platforms="android,ios" --ios-bundle-id="$PACKAGE_NAME" --macos-bundle-id="$PACKAGE_NAME" --android-package-name="$PACKAGE_NAME" --token="$FIREBASE_TOKEN"

      # Increment build number
      - name: Increase build number
        run: echo $(( $BUILD_NUMBER + 1 )) >> $GITHUB_ENV

      # Build apk 
      - name: Build APK
        run: flutter build apk --build_number = $BUILD_NUMBER
        
      # Upload apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
         name: release-apk
         path: build/app/outputs/flutter-apk/app-release.apk
        
      # Distribute apk
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
            serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
            groups: testers
            file: build/app/outputs/flutter-apk/app-release.apk
